# Generated by Django 3.1.1 on 2020-10-08 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201008_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 8, 52, 24, 695448)),
        ),
    ]
