# Generated by Django 3.1.1 on 2020-10-08 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201008_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 9, 12, 40, 906834)),
        ),
    ]
