# Generated by Django 3.1.1 on 2020-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201008_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
