# Generated by Django 3.1.2 on 2020-10-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201009_0419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
